# Generated by Django 3.0.6 on 2021-02-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('userName', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
